#! /bin/sh
# /etc/init.d/ksm: Enable KSM
#
# written by EBK21 <eebssk1@ebktech21.xyz>

### BEGIN INIT INFO
# Provides:          ksm
# Required-Start:    mountkernfs $local_fs
# Required-Stop:
# Should-Start:      udev module-init-tools
# X-Start-Before:    $network
# Default-Start:     2 3 4 5
# Default-Stop:     0 1 6
# Short-Description: Enable ksm
# Description:  Enable ksm
### END INIT INFO

. /lib/lsb/init-functions

STATUS=0

error () {
exit $STATUS
}

whprestepfail () {
if [ $? != 0 ]
then
log_failure_msg "$@"
STATUS=1
error
fi
}

whstepfail () {
log_failure_msg "$@"
STATUS=1
error
}

checkandset () {
if [ $? != 0 ]
then
STATUS=1
fi
}

whfailbystat () {
if [ $STATUS != 0 ]
then
whstepfail "$@"
fi
}

PTS=124
SL=44

case "$1" in
start)
log_begin_msg "Start enable zram\n"
if [ ! -e /sys/kernel/mm/ksm ]
then
whstepfail "Kernel does not support KSM,exiting"
fi
log_action_msg "Setting some ksm param"
echo $PTS > /sys/kernel/mm/ksm/pages_to_scan
whprestepfail "Failed to set ksm param pages_to_scan"
echo  $SL > /sys/kernel/mm/ksm/sleep_millisecs
whprestepfail "Failed to set ksm param sleep_millisecs"
log_action_msg "Starting ksm"
echo 1 > /sys/kernel/mm/ksm/run
whprestepfail "Failed to start ksm"
log_action_msg "Done"
log_end_msg $STATUS
;;
stop)
log_begin_msg "Stopping ksm"
echo 0 > /sys/kernel/mm/ksm/run
whprestepfail "Failed to stop ksm"
log_end_msg $STATUS
;;
status)
;;
esac

